# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crypto_file_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class Ui_CryptoWidget(QWidget):
    def __init__(self, file: str):
        super(Ui_CryptoWidget, self).__init__()
        self.originalFile = file
        self.encryptedFile = None
        self.decryptedFile = None
        self.crypto_thread = None

    def setupUi(self, CryptoWidget):
        CryptoWidget.setObjectName("CryptoWidget")
        CryptoWidget.resize(705, 41)
        CryptoWidget.setProperty("originalFile", "")
        CryptoWidget.setProperty("encryptedFile", "")
        CryptoWidget.setProperty("decryptedFile", "")
        self.horizontalLayout = QtWidgets.QHBoxLayout(CryptoWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileButton = QtWidgets.QPushButton(CryptoWidget)
        self.fileButton.setMinimumSize(QtCore.QSize(100, 0))
        self.fileButton.setFlat(True)
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout.addWidget(self.fileButton)
        self.workButton = QtWidgets.QPushButton(CryptoWidget)
        self.workButton.setMinimumSize(QtCore.QSize(100, 0))
        self.workButton.setCheckable(True)
        self.workButton.setChecked(False)
        self.workButton.setObjectName("workButton")
        self.horizontalLayout.addWidget(self.workButton)
        self.progressBar = QtWidgets.QProgressBar(CryptoWidget)
        self.progressBar.setMinimumSize(QtCore.QSize(100, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)

        self.retranslateUi(CryptoWidget)
        QtCore.QMetaObject.connectSlotsByName(CryptoWidget)

    def retranslateUi(self, CryptoWidget):
        _translate = QtCore.QCoreApplication.translate
        CryptoWidget.setWindowTitle(_translate("CryptoWidget", "Form"))
        self.fileButton.setText(_translate("CryptoWidget", "PushButton"))
        self.workButton.setText(_translate("CryptoWidget", "Зашифровать"))
